title: Ítalo Marcos
description: Um blog sobre python, desenvolvimento web com django, flask e mais algumas coisas legais =D
author: Ítalo Marcos
avatar: /me.png
email: italomarcos.dev@gmail.com
skin: midnight


plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
# twitter:
#   username: ngzhio
#   card: summary
logo: logo.png
social:
  name: Ítalo Marcos
  links:
    # - https://twitter.com/ngzhio
    # - https://www.facebook.com/ngzhio
    - https://www.linkedin.com/in/%C3%ADtalo-marcos-boaventura-siqueira-38b4a9191/
    - https://github.com/italo11marcos
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: pt-br
